# Generated by Django 5.0.14 on 2026-08-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='user_limit',
            field=models.PositiveIntegerField(default=1, help_text='Maximum times a single user can redeem this coupon'),
        ),
    ]
