# Generated by Django 5.0.14 on 2026-08-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='ETERNAAURA', max_length=150)),
                ('contact_email', models.EmailField(default='support@eternaaura.com', max_length=254)),
                ('support_phone', models.CharField(default='+91 98765 43210', max_length=30)),
                ('store_address', models.TextField(default='701, Eterna Towers, Bandra Kurla Complex, Mumbai, Maharashtra 400051')),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('standard_shipping_fee', models.DecimalField(decimal_places=2, default=150.0, max_digits=8)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=5000.0, max_digits=8)),
                ('enable_razorpay', models.BooleanField(default=True)),
                ('enable_stripe', models.BooleanField(default=True)),
                ('enable_cod', models.BooleanField(default=True)),
                ('enable_upi', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
