# Generated by Django 5.0.14 on 2026-07-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('unspecified', 'Prefer not to say'), ('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='unspecified', max_length=15),
        ),
    ]
