# Generated by Django 5.0.14 on 2026-08-04 13:19

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[config.validators.FileExtensionValidator(['.jpg', '.jpeg', '.png', '.webp']), config.validators.MaxFileSizeValidator(5)]),
        ),
    ]
