# Generated by Django 5.0.14 on 2026-08-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff_role',
        ),
    ]
