# Generated by Django 5.0.14 on 2026-08-04 13:19

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to='reviews/', validators=[config.validators.FileExtensionValidator(['.jpg', '.jpeg', '.png', '.webp']), config.validators.MaxFileSizeValidator(5)]),
        ),
    ]
