# Generated by Django 5.0.14 on 2026-08-04 13:19

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[config.validators.FileExtensionValidator(['.jpg', '.jpeg', '.png', '.webp']), config.validators.MaxFileSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='collection',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/', validators=[config.validators.FileExtensionValidator(['.jpg', '.jpeg', '.png', '.webp']), config.validators.MaxFileSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(upload_to='banners/', validators=[config.validators.FileExtensionValidator(['.jpg', '.jpeg', '.png', '.webp']), config.validators.MaxFileSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[config.validators.FileExtensionValidator(['.jpg', '.jpeg', '.png', '.webp']), config.validators.MaxFileSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/video_thumbs/', validators=[config.validators.FileExtensionValidator(['.jpg', '.jpeg', '.png', '.webp']), config.validators.MaxFileSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=models.FileField(upload_to='products/videos/', validators=[config.validators.FileExtensionValidator(['.mp4', '.webm', '.mov', '.avi']), config.validators.MaxFileSizeValidator(50)]),
        ),
    ]
