# Generated by Django 5.0.14 on 2026-08-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_image_alter_collection_banner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herobanner',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='herobanner',
            name='cta_url',
        ),
    ]
