# Generated by Django 5.0.14 on 2026-08-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_herobanner_cta_label_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_published', 'is_new_arrival'], name='catalog_pro_is_publ_b5b331_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_published', 'is_best_seller'], name='catalog_pro_is_publ_dfaa46_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_published', 'is_trending'], name='catalog_pro_is_publ_c1f529_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_published', 'category'], name='catalog_pro_is_publ_cba3a6_idx'),
        ),
    ]
